### ISSUE TITLE
mps-youtube is not streaming music

### ISSUE THREAD

**Issue by yamsu** [mps-youtube/mps-youtube#470] opened 2016-04-07 11:34 UTC
I just updated to ubuntu 14.04 64bit and mps-youtube from pip3. All aspects seems fine expect for the following:

1. songs do not stream anymore, mps waits for the song to download before playing it.
2. the song progress bar does not show.

Is anyone else having this issue. I have also tried this with the developer editions of mps-youtube and pafy

**Comment by uNouss** [comment] 2016-04-08 16:06
hello i have similar issue after i update mpsyt to latest developer version of mps-youtube and pafy. if i try to stream audio or video, mpsyt wait but dont launch anything :(

**Comment by ids1024** [comment] 2016-04-10 16:16
Try installing youtube-dl with `pip3 install youtube_dl`.

**Comment by uNouss** [comment] 2016-04-10 21:06
@ids1024 i have youtube_dl 
here my config 
![2016-04-10-230149_636x357_scrot](https://cloud.githubusercontent.com/assets/15982321/14413086/94b6c024-ff70-11e5-83dc-32636b96a09b.png)

and here the issue 
![2016-04-10-225726_636x357_scrot](https://cloud.githubusercontent.com/assets/15982321/14413090/acfbba22-ff70-11e5-9871-542d6954acaf.png)

**Comment by ids1024** [comment] 2016-04-10 21:28
Are you using mpv or mplayer?

**Comment by uNouss** [comment] 2016-04-10 21:30
@ids1024 i use mpv

**Comment by ids1024** [comment] 2016-04-10 21:39
I'm not really sure what the problem is.  Does mplayer work?

**Comment by uNouss** [comment] 2016-04-10 21:48
@ids1024 mplayer does not work

![2016-04-10-234728_636x357_scrot](https://cloud.githubusercontent.com/assets/15982321/14413315/af09b0e8-ff76-11e5-96c5-db98d3cc9cab.png)

**Comment by ids1024** [comment] 2016-04-10 21:56
Ok, try switching back to mpv, install the debug branch of mpsyt, and start with `mpsyt --debug`. Then it will (hopefully) display more information when you try to play something.

**Comment by uNouss** [comment] 2016-04-10 22:52
@ids1024 how can i install the debug branch ?

**Comment by ids1024** [comment] 2016-04-10 22:53
`sudo pip3 install --upgrade https://github.com/mps-youtube/mps-youtube/archive/develop.zip`

**Comment by uNouss** [comment] 2016-04-10 22:56
i have this with `mpsyt --debug` after i install the debug branch
![2016-04-11-005459_636x357_scrot](https://cloud.githubusercontent.com/assets/15982321/14413627/1b2e3498-ff80-11e5-8d7a-1aa39b4858cb.png)

**Comment by ids1024** [comment] 2016-04-10 22:57
What happens when you try to play a song, while in debug mode?

**Comment by uNouss** [comment] 2016-04-10 23:03
hmm nothing stream, i have this
![2016-04-11-005932_636x357_scrot](https://cloud.githubusercontent.com/assets/15982321/14413656/f5247eaa-ff80-11e5-80f9-b0bff1395180.png)

 but if i try to run this with mpv 
![2016-04-11-010106_636x358_scrot](https://cloud.githubusercontent.com/assets/15982321/14413659/030b90ee-ff81-11e5-8c32-1d69c3c0920f.png)

**Comment by uNouss** [comment] 2016-04-10 23:04
hmm after 5 7mn i have stream. i launch again for test

**Comment by uNouss** [comment] 2016-04-10 23:15
@ids1024 yes after i upgrade youtube-dl with `pip3 install --upgrade https://github.com/rg3/youtube-dl/archive/master.zip` now mpsyt work correctly.

thank you for your help ^_^

**Comment by ids1024** [comment] 2016-04-10 23:33
Good to see that its working. @yamsu does updating youtube-dl fix the problem for you?

**Comment by yamsu** [comment] 2016-04-13 13:16
Hi,
Sorry to have disappeared. Yes the update of youtube-dl has done the trick. Thanks. But i still dont get the old progress bar, i.e [======>               ]

But i have not updated mpsyt to the debug version. Should I try that?

**Comment by ids1024** [comment] 2016-04-15 02:21
@yamsu I seem to be getting the same behavior. I'll look into it.

**Comment by ids1024** [comment] 2016-04-16 16:30
It looks like the problem is with the latest version of mplayer renaming the socket input argument.

**Comment by ids1024** [comment] 2016-04-16 16:39
That issue should be fixed in https://github.com/mps-youtube/mps-youtube/commit/7c2470f1eea4089014f38f451277623999c01c14.

**Closed** 2016-06-27 17:19 UTC
Labels: bug, fix applied
