### ISSUE TITLE
some videos crash mps-yt

### ISSUE THREAD

**Issue by dottdottdott** [mps-youtube/mps-youtube#379] opened 2015-11-13 19:53 UTC
I noticed it a few days ago, there are some videos that just don't play anymore with mps-yt and crash it. I think youtube changed something, because i also can't play those videos with the youtube plugin from KODI.
I get this error:
Traceback (most recent call last):                                              
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.5', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 4780, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 4680, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3450, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 3543, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 2104, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 145, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1076, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 1102, in fetch_basic
    smaps, js_url, funcs, dashurl = get_js_sm(self.videoid)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 704, in get_js_sm
    mainfunc = _get_mainfunc_from_js(javascript)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 364, in _get_mainfunc_from_js
    function = _extract_function_from_js(funcname, js)
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 339, in _extract_function_from_js
    args, body = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

one of the video that is no working would be tWva8PawQi4

**Comment by hypha** [comment] 2015-11-13 21:50
Hi, I had the same problem but after updating pafy, the problem resolves.
Maybe try that first (if you are not on the latest version).

Cheers

**Comment by ids1024** [comment] 2015-11-13 23:23
Essentially a duplicate of #376 and #378. Update pafy.

**Closed** 2015-12-20 22:27 UTC
