### ISSUE TITLE
Playlist error

### ISSUE THREAD

**Issue by VexillePC** [mps-youtube/mps-youtube#459] opened 2016-03-11 19:06 UTC
Hey! I have a little problem. 
If i wanna play my playlist, i get this image. Can anybody help to me?
[https://p1.picsto.re/3SsWV.png](https://p1.picsto.re/3SsWV.png)

**Comment by ids1024** [comment] 2016-03-11 19:08
Duplicate of  #444. It should be fixed by using the latest pafy version, with the youtube-dl backend (enabled by default if youtube-dl is installed).

**Closed by ids1024** 2016-03-11 19:08 UTC

**Comment by VexillePC** [comment] 2016-03-11 19:17
I'm using the latest pafy version :(

**Comment by ids1024** [comment] 2016-03-11 19:19
Do you have youtube-dl installed?

**Comment by VexillePC** [comment] 2016-03-11 19:22
youtube-dl? where can i find it?

**Comment by ids1024** [comment] 2016-03-11 19:24
`pip install youtube_dl`

**Comment by VexillePC** [comment] 2016-03-11 19:30
I do something wrong?
[https://p1.picsto.re/iAQCg.png](https://p1.picsto.re/iAQCg.png)

**Comment by ids1024** [comment] 2016-03-11 19:35
I don't quite understand what you did. Did you install `youtube_dl` with pip?

**Comment by VexillePC** [comment] 2016-03-11 19:44
oh i installed with windows terminal (cmd)

**Comment by ids1024** [comment] 2016-03-11 19:47
You shouldn't be trying to execute `backend_youtube_dl` as a script. It is not one.

You need to run the command `pip install youtube_dl` in the terminal, or otherwise install the module.

**Comment by VexillePC** [comment] 2016-03-11 20:06
I give up
I'm stupid for that. :-/
