### ISSUE TITLE
Titles are not escaped when subprocess is spawned

### ISSUE THREAD

**Issue by dreadnaut** [mps-youtube/mps-youtube#341] opened 2015-08-18 14:56 UTC
If a video title contains special shell characters such as `&` or `|`, these will be interpreted by the shell.

Easily reproduced with latest stable on Windows:
- search for "& some-command", for example `/"&notepad"` or `/"& cmd"`
- play any result with a title containing the special character
- a Notepad or Prompt window will open

**Comment by ids1024** [comment] 2015-08-18 15:25
I think this is a duplicate of #321. If so, the bug is fixed in git (see commit 0b103fc).

**Comment by dreadnaut** [comment] 2015-08-18 15:44
Indeed it is. Apologies, I searched for existing issues but only among open ones.

**Closed** 2015-08-18 15:45 UTC
