### ISSUE TITLE
Allow detaching player from the mpsyt terminal window

### ISSUE THREAD

**Issue by Vrihub** [mps-youtube/mps-youtube#563] opened 2016-11-18 12:10 UTC
Feature request: give the user the option of running the video player without keeping the main mpsyt terminal window busy.

All the information displayed in the mpsyt terminal while watching a video (time length, progress bar) is already available in the video player, this is also true for the seek and volume controls.

Instead, "detaching" the player from the mpsyt terminal would allow the user to run mpsyt commands while watching a video, e.g. reading the video info screen, or comments etc., which seems much more valuable to me.

**Comment by ids1024** [comment] 2016-11-19 02:42
Duplicate of #127.

**Closed by ids1024** 2016-11-19 02:42 UTC
