### ISSUE TITLE
Exception from pafy/backend_youtube_dl.py

### ISSUE THREAD

**Issue by patraulea** [mps-youtube/mps-youtube#570] opened 2016-12-19 11:05 UTC
Installed mpsyt-0.2.7.1 and youtube-dl 2016.12.18 via pip3 and configured mpv as player. Playing '*' from the playlist below threw this stack:

```
Showing YouTube playlist Straight Outta Compton Movie Soundtrack                                 
> Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bogdan/.local/lib/python3.5/site-packages/mps_youtube/streams.py", line 171, in _preload
    streamlist = get(song)
  File "/home/bogdan/.local/lib/python3.5/site-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/home/bogdan/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/home/bogdan/.local/lib/python3.5/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/bogdan/.local/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/bogdan/.local/lib/python3.5/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/home/bogdan/.local/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ids1024** [comment] 2016-12-19 18:40
Duplicate of #565. See my comment for code that should fix the bug. It has not been merged though, since there should be a category, and it would be better to find the source of the issue.

**Closed by ids1024** 2016-12-19 18:40 UTC
