### ISSUE TITLE
Feature Request: Global volume

### ISSUE THREAD

**Issue by justijndepover** [mps-youtube/mps-youtube#557] opened 2016-11-02 11:00 UTC
Hi,

Is it possible to make the volume global? If you currently change the volume and select a different song, the volume is back at 100%. It would be nicer if it stays the same.

**Comment by ids1024** [comment] 2016-11-03 05:09
Duplicate of #145.

This is arguably an issue with the player (mpv or mplayer) rather than mpsyt.

**Closed** 2016-11-03 05:09 UTC
Labels: duplicate
