### ISSUE TITLE
fork mpv

### ISSUE THREAD

**Issue by eoli3n** [mps-youtube/mps-youtube#532] opened 2016-09-28 17:35 UTC
Hi
Is there a way to fork mpv player, to let user browse videos while playing another one ?

**Comment by ids1024** [comment] 2016-09-29 05:52
Duplicate of #127. This feature is more or less planned for the future, but it is not entirely trivial to implement, so no guarantees on when that might happen.

**Closed by ids1024** 2016-09-29 05:52 UTC
