### ISSUE TITLE
Traceback error at start

### ISSUE THREAD

**Issue by freeasinbear** [mps-youtube/mps-youtube#566] opened 2016-12-10 19:55 UTC
I'm getting this error when I try to run mpsyt. I tried upgrading pip3 and uninstalling/reinstalling mpsyt but I still get it: 
(I'm using Debian 64 bit and this error never happened before)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pafy/util.py", line 27, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/init.py", line 58, in init
    cache.load()
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/cache.py", line 34, in load
    pafy.load_cache(cached['pafy'])
  File "/usr/local/lib/python3.5/dist-packages/pafy/pafy.py", line 182, in load_cache
    set_categories(newcache.get('categories', {}))
  File "/usr/local/lib/python3.5/dist-packages/pafy/pafy.py", line 169, in set_categories
    catinfo = call_gdata('videoCategories', query)
  File "/usr/local/lib/python3.5/dist-packages/pafy/util.py", line 35, in call_gdata
    raise GdataError(errmsg)
pafy.util.GdataError: Youtube Error 403: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=422897895433

**Comment by freeasinbear** [comment] 2016-12-10 19:56
I just found out that if I run mpsyt with sudo it works.. but I don't think this is a solution

**Comment by ids1024** [comment] 2016-12-10 19:59
Duplicate of #551. You can register your our API key with Google and then use it with `set api_key API_KEY`.

> I just found out that if I run mpsyt with sudo it works.. but I don't think this is a solution

Are you sure? That would be rather odd.

**Comment by freeasinbear** [comment] 2016-12-10 20:02
Yeah, it also doesn't make me install/uninstall it without sudo.. it gives me the same error. If i remember correctly sudo privileges weren't needed for pip, right?

Anyway what is the API key to register with it? Anyway I don't use mpsyt *that* much.. especially lately.. I used it with more frequency in the past and never had this issue from Google

**Comment by freeasinbear** [comment] 2016-12-11 16:48
Ok for some reasons I don't see the traceback error anymore (I still see it on other python software though).. and the google's one should have fixed itself at midnight, by resetting itself.

Thanks anyway

**Closed** 2018-07-01 17:18 UTC
