### ISSUE TITLE
Sign in to confirm your age 

### ISSUE THREAD

**Issue by m0t420** [mps-youtube/mps-youtube#1024] opened 2019-10-21 18:21 UTC
ERROR: Content Warning
This video may be inappropriate for some users.
       Sign in to confirm your age

How to sign in with mpsyt? I can not find this option

Thanks

**Comment by Nojus297** [comment] 2019-10-26 21:47
Thumbs up your own issue?
Anyway, the problem is with _pafy_
See https://github.com/mps-youtube/pafy/issues/241#issuecomment-546641978

**Comment by hrnr** [comment] 2019-11-10 20:29
Closing as duplicate. This issue is tracked in pafy as noted above

**Closed by hrnr** 2019-11-10 20:29 UTC
Labels: duplicate
