### ISSUE TITLE
After upgrading ubuntu mate to 15.10 ImportError: No module named 'UserString'

### ISSUE THREAD

**Issue by josifoski** [mps-youtube/mps-youtube#373] opened 2015-11-05 14:53 UTC
aleksandar@aleksandar-AMILO-Li-2727:~$ mpsyt
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/__init__.py", line 2, in <module>
    init()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 868, in init
    init_cache()
  File "/usr/local/lib/python3.4/dist-packages/mps_youtube/main.py", line 1040, in init_cache
    cached = pickle.load(cf)
ImportError: No module named 'UserString'

I've uninstalled, installed again with pip3 still same error occure

**Comment by josifoski** [comment] 2015-11-05 18:22
Solved with 'brute force', clean install of ubuntu-mate 15.10

**Comment by ids1024** [comment] 2015-11-08 18:14
Hm, I don't know quite the cause of this.  I'll just close the issue, if you got it to work with a clean install.

**Closed by ids1024** 2015-11-08 18:14 UTC

**Comment by jdsampayo** [comment] 2015-12-09 16:07
This type of errors "No module named" can be solved deleting the directory:
    rm -rf ~/.config/mps-youtube/

See https://github.com/mps-youtube/mps-youtube/issues/392

**Comment by trinaldi** [comment] 2016-02-27 14:02
@ids1024:
@jdsampayo That worked for me. Thanks!
