### ISSUE TITLE
mplayer keys doesn't work on win7 

### ISSUE THREAD

**Issue by eskiq** [mps-youtube/mps-youtube#819] opened 2018-04-01 09:26 UTC
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.03.26.1
Python version     : 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Processor          : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-7-6.1.7601-SP1
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : C:\Users\Nea\AppData\Roaming\mps-youtube

While playing audio only, there is no control over playback. Pressing keys like Space or right arrow doesn't do anything. Do I need additional configuration to make them working?

**Comment by ritiek** [comment] 2018-08-24 13:58
I know this is pretty late for a reply.

 I had a similar problem in Windows recently and
```
set player mpv.com
```
worked for me.

Also see #465.

**Comment by eskiq** [comment] 2018-12-12 17:31
Thank you, I will check it next time :D

**Comment by marc1uk** [comment] 2020-03-31 15:20
Duplicate of #1005 and #561, the latter of which gives the solution that worked for me:
`set player mpv.com`

**Closed** 2020-06-28 22:27 UTC
