### ISSUE TITLE
Search during playback

### ISSUE THREAD

**Issue by lorenzomaieru** [mps-youtube/mps-youtube#370] opened 2015-10-31 16:07 UTC
this is pretty much a mirror of [mps/issues/34](https://github.com/np1/mps/issues/34), but considering that project hasn't had any activity in over a year, might as well try here.

Searching without having to stop the playing music would be great.
Additionally, if one could add the newly found results to the currently playing list--instead of overriding it--that also would be amazing.

I'm interested in knowing if this is something that is planned and/or what tasks do you guys think it would take to implement it.

Right now, it's the only couple of features that I keep wishing for.

**Comment by ids1024** [comment] 2015-10-31 16:10
Duplicate of #127. Yes, this functionality is intended, but it is not simple to implement.

**Closed by ids1024** 2015-10-31 16:10 UTC
