### ISSUE TITLE
HTTP is not supportet

### ISSUE THREAD

**Issue by Hexical0** [mps-youtube/mps-youtube#1044] opened 2019-12-23 21:12 UTC
ERROR: Mfct_rLqHoI: Youtube said: HTTP is not supported

Just trying to play/download music from youtube
version 0.2.8
Windows 10
mpv

**Comment by DBX12** [comment] 2019-12-24 15:36
Can confirm this happens for me as well:
`mpsyt --version`

```
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.06.21
Python version     : 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.15.0-72-generic-x86_64-with-LinuxMint-19.1-tessa
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/dbx12/.config/mps-youtube
env:TERM           : screen
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US
```

**Comment by dnhuan** [comment] 2019-12-29 13:41
`pip3 install --upgrade youtube-dl && pip3 install --upgrade mps-youtube`

Solved my problem by upgrading mpsyt to the lasted version.

**Comment by ritiek** [comment] 2020-01-10 16:30
Seems like a duplicate of #986. One can fix this by following what @dnhuan mentioned and also upgrading pafy with `pip3 install pafy -U`.

**Closed by ritiek** 2020-01-10 16:30 UTC
