### ISSUE TITLE
Getting the Youtube Error 403!

### ISSUE THREAD

**Issue by CharlesCage** [mps-youtube/mps-youtube#977] opened 2019-05-06 02:30 UTC
## Issue / Suggestion

Receiving the following error:
Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.

**Comment by ritiek** [comment] 2019-05-07 05:07
It seems like user base has grown more than a single API key can handle.

You could generate your own YouTube Data API key (Guide: https://elfsight.com/help/how-to-get-youtube-api-key/) and then set this key in mpsyt with:
```
> set api_key AIzaSyC.......
```

It should work now.

**Comment by lightonflux** [comment] 2019-05-11 13:32
If the amount of requests for that key is a problem, why can you play the next song without issue?

**Comment by ritiek** [comment] 2019-05-12 09:07
> If the amount of requests for that key is a problem, why can you play the next song without issue?

@lightonflux I just tried and it seems like there are 2 different causes for the 403 error.

The first one is the one reported in this issue:
> Youtube Error 403: The request cannot be completed because you have exceeded your quota.

which is caused due to making more API requests in a day than the API key allows for.

The second error (the one I think you're talking about) which I receive is simply:
> Problem playing last item: HTTP Error 403: Forbidden

To me, this seems like a bug with the YouTube API itself. Pick up any YouTube video and get its audio URL with youtube-dl and like 1/5 times it would result in a forbidden URL. Such as:

```
$ curl --head $(youtube-dl -x https://youtube.com/watch?v=p_vSh1DUsD4 -g)
```

And it looks like mpsyt caches these audio URLs so if you get this forbidden error on a track once, you will always get this same error whenever you try to play that same track through mpsyt. Until you delete the URL cache file in `~/.config/mps-youtube/cache_py_3.*` and try your luck again.

**Comment by ritiek** [comment] 2019-05-12 09:15
What I think we could do to workaround this error would be test beforehand if the generated audio URL gives a 403 forbidden. If it does, keep retrying.

**Comment by PatOConnor43** [comment] 2019-05-13 17:05
I can confirm that deleting `~/.config/mps-youtube/cache_py_3.*` solved the issue for me. Thanks for the workaround!

**Comment by eskiq** [comment] 2019-05-13 18:08
I'm heaving problem "https: HTTP error 403 Forbidden" on some videos while using terminal and command mpv m.m3u, but never had any problem playing same list outside terminal. Using terminal I still can go back and load something that was not loaded in the first place, while mps will not load it at all. There is 1 of 3 commands that I use in my mpv.conf depending if I wanna watch with or without video and they gave a little different results what will play in terminal and what not.
#ytdl-format=bestvideo[height<=?720][fps<=?60][vcodec=?vp9]+bestaudio/best
#ytdl-format=bestvideo[height<=?720][fps<=?60]+bestaudio/best
ytdl-format=bestaudio/best
also tried mpv m.m3u -no-video in terminal
With mpv player everything is working fine with or without video.
I feel like in terminal its trying to load stuff a little faster, and maybe that is cousing some problems. BTW I'm on Arch LinuxD and my friend is on Manjaro, and we both have same issue with mps so I assume that this problem is very common.

**Comment by dgalaktionov** [comment] 2019-05-15 09:42
I kept getting the 403 error even though I've tried both changing the API key and removing the cache files. After looking into the issue, it turned out youtube has made a slight change to their API again. I've **upgraded youtube-dl** as they seem to have fixed it in https://github.com/ytdl-org/youtube-dl/commit/027ffdca0d3174963a4269ce8de8519cfed7a12c and had zero issues for now.

**Comment by eskiq** [comment] 2019-05-16 08:03
This fixed also all my problems and now everything is working perfectly fine.

**Comment by ritiek** [comment] 2019-06-07 16:13
Closing this as solved.

**Closed by ritiek** 2019-06-07 16:13 UTC

**Comment by elquimista** [comment] 2019-06-18 10:08
@dgalaktionov I upgraded youtube-dl too to 2019-06-08 version and made sure I'm using latest version of mps-youtube, but when `mpsyt --version` shows it's using youtube-dl version 2019-04-04, thus I still get 403 forbidden error. Is there any way to force mpsyt to use the latest youtube-dl version?

**Comment by dgalaktionov** [comment] 2019-06-18 10:11
@elquimista this should not happen. Are you using pip? Maybe you upgraded the package for python 2 instead of python3? Try to upgrade everything with `pip3`.

**Comment by elquimista** [comment] 2019-06-18 10:56
@dgalaktionov I use mac so I'm using homebrew. I installed like this:
```sh
brew install mps-youtube youtube-dl
```

**Comment by dgalaktionov** [comment] 2019-06-18 11:02
@elquimista well I've never used homebrew but apparently there is a `--with-python3` you can add, so it would be like this:
```
brew install mps-youtube youtube-dl --with-python3
```

Also you could check the [configuration guidelines for pip packages](https://docs.brew.sh/Homebrew-and-Python).

**Comment by elquimista** [comment] 2019-06-18 11:14
@dgalaktionov `--with-python3` option is no longer valid. I ended up installing mps-youtube and youtube-dl using pip3 and mpv with homebrew. And now it's working again. Thanks for your help.

**Comment by rune2291** [comment] 2020-08-05 10:20
I get this message
[91mYoutube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.[0m[0m

installed it with pip3.

I have tried upgrading youtube-dl and reinstalling.
it runs on  windows 
I guess theres something with the API mentioned above.
hope someone can help out.
best regards.

**Comment by AchmadFathoni** [comment] 2020-08-06 00:45
> I get this message
> �[91mYoutube Error 403: The request cannot be completed because you have exceeded your href="/youtube/v3/getting-started#quota">quota.�[0m�[0m
> 
> i have omitted the html tags 'a' and '/a' around href... quota
> 
> installed it with pip3.
> 
> I have tried upgrading youtube-dl and reinstalling.
> it runs on windows
> I guess theres something with the API mentioned above.
> hope someone can help out.
> best regards.

Same here

**Comment by goldencut** [comment] 2021-05-06 11:41
Getting and setting new API key worked for me on latest on Solus (Linux).

**Comment by 2play** [comment] 2022-02-02 22:57
API ddnt work on:

` mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2019.01.17
Python version     : 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0]
Processor          :
Machine type       : armv7l
Architecture       : 32bit, ELF
Platform           : Linux-5.10.63-v7+-armv7l-with-debian-10.11
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/pi/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
pi@playbox:~ $ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.8-0+deb10u1+rpt1`
