### ISSUE TITLE
Exclude certain formats

### ISSUE THREAD

**Issue by fa7ad** [mps-youtube/mps-youtube#388] opened 2015-11-27 04:57 UTC
How would I go about disabling a certain format, better yet choose a particular format for audio-only playback?

I want to avoid `webm 50k` audio cuz the format is terrible and produces absolute shitty sound.

**Comment by ids1024** [comment] 2015-11-27 17:25
There is currently no way to do that.

If the problem is that it is selecting too low quality of a format, that is a bug, which should already be fixed in git.

**Comment by fa7ad** [comment] 2015-11-28 16:27
well then, i guess you can consider it a bug. I'm using the dev version right now, even this has the same problem

**Closed** 2017-01-15 15:26 UTC
