### ISSUE TITLE
Media keys support

### ISSUE THREAD

**Issue by Atlantic777** [mps-youtube/mps-youtube#303] opened 2015-06-02 21:41 UTC
It would be nice to have media keys support as in many standard media players. There are X86Audio* keys. I'm not sure what's the best way to have this implemented, but LIRC may be of some help.

**Comment by lol768** [comment] 2015-06-02 22:10
These already seem to work for me. Presumably my DE is using mpris when I hit Play/Pause/Forward/Back?

**Comment by Atlantic777** [comment] 2015-06-02 22:21
Hm, I'm using the i3 wm so it may be the problem. I didn't know that it's already supported and didn't find anything in issues but that means that I need help. :)

I've tried it with unity DE (default Ubuntu 14.04 install) and I still can't use media keys. I tried installing mpris-remote (a CLI app for controlling MPRIS-compliant players) and I just got message that there's no players running.

```
No MPRIS-compliant player found running.
```

Any ideas how to debug this?

**Comment by ids1024** [comment] 2015-06-02 22:26
I have media keys working in dwm. I don't know why mpris-remote is not working, but playerctl works for me. I have bindings set up with sxhkd, but you could use xbindkeys instead.

**Comment by lol768** [comment] 2015-06-02 22:29
@Atlantic777 

I actually use i3 on my laptop and I was trying to play with mpris-remote today. I had exactly the same issue as you. As it happened I was trying to get the name of the current song to put in my i3status bar. In the end, I did a "ps -ef | grep mpv" + a regex, but it's interesting it doesn't work and I'm not sure why.

The DE where the buttons do work is cinnamon (I use it on my desktop). It displays the album art correctly and the buttons work.

**Comment by Atlantic777** [comment] 2015-06-02 22:48
Thanks guys, it works. Playerctl is working fine and I just added key binding in my i3 config. In case that somebody stubmles upon this, here's how to do it:

1) install playerctl dependencies ( gobject-introspection and gtk-doc-tools on ubuntu)
2) clone playerctl repo  - https://github.com/acrisci/playerctl
3) compile and install as in playerctl readme
4) add this to your ~/.i3/config

```
#MPS keys
bindsym XF86AudioPlay exec "playerctl play-pause"
bindsym XF86AudioNext exec "playerctl next"
bindsym XF86AudioPrev exec "playerctl previous"
```

5) Restart i3 (probably mod+shift+R

@lol768 I see that `playerctl metadata xesam:title` gives you the name of song. What's the problem with i3bar? I would make use of song in the i3bar, too. :)

**Comment by hrnr** [comment] 2015-06-02 23:09
Just for future reference `mpris-remote` doesn't work because it supports only MPRISv1, while we are using MPRISv2. Too bad `playerctl` is not packaged on most distros.

**Comment by Atlantic777** [comment] 2015-06-02 23:14
Maybe we can do something with packaging `playerctl`. ;)

**Comment by ids1024** [comment] 2015-06-02 23:19
@hrnr How difficult do you think it would be to add mpris 1 support to mpsyt? Probably not worthwhile, but it could be useful for some software.

**Comment by hrnr** [comment] 2015-06-03 07:29
It would require new `Mpris2MediaPlayer` class. It's probably not worth it as mainline players like Rhytmbox already dropped their MPRIS 1 support. And others (Spotify) always implemented MPRIS 2 only. Also, desktop enviroments with MPRIS support (like cinnamon) are ignoring MPRIS 1.

@Atlantic777 Thats a good point. `playerctl` is a good piece of software.

**Comment by orschiro** [comment] 2015-06-03 12:20
Dear all, 

Thanks for opening this thread! I was precisely looking into the same request. mps-youtube is great and there is even a way to integrate it into the sound indicator of elementaryOS and Ubuntu: 

![nimbus-image-1433333924197](https://cloud.githubusercontent.com/assets/170947/7959669/75c498c8-09fb-11e5-80b2-bf873b82586a.png)
Howto: http://www.webupd8.org/2015/05/mps-youtube-migrates-to-youtube-api-v3.html

However, as you noted above there is not media key support for Ubuntu or eOS. 

The steps you describe seem to work for WMs such as dwm or i3. 

> The DE where the buttons do work is cinnamon (I use it on my desktop). It displays the album art correctly and the buttons work.

This is interesting. Does anyone know how Cinnamon support media keys by default and why Ubuntu and eOS doesn't?

Thankfully,

Robert

**Comment by hrnr** [comment] 2015-06-03 17:05
it is supported via MPRIS (the same way applet is communicating with mps-youtube). As far as I know, ubuntu is not using mpris for media keys, it uses `gnome-media-keys` for that.

However you can simply bind your media keys to playerctl as mentioned above and it will work the same way as on cinnamon.

**Comment by orschiro** [comment] 2015-06-05 08:03
@hrnr 

> EDIT: If you don't want to install playerctl, I've created a simple shell script with the same basic functionality (works for example above). See https://gist.github.com/hrnr/43d926875577f6c3fd70

Thanks for your efforts! I am not sure if I can use it. If I try to map it to my media keys, then obviously it conflicts with the existing mapping of the media keys of my elementaryOS installation. 

![image](https://cloud.githubusercontent.com/assets/170947/8001848/0fe62baa-0b6a-11e5-84f7-04c824e3049c.png)

**Comment by hrnr** [comment] 2015-06-07 09:24
What you get is expected behaviour. If you want similar behaviour to cinnamon, you should reassign those keys to my script/playerctl. This way you can control both mps-youtube and elementary OS player and others (like rhythmbox).

I tried  to test elementary OS player that and it seems to support MPRIS correctly, but wasn't able to import any songs (what?). Probably you should try at first running `./mprisctl pause` and see if that pauses elementary OS player.

**Comment by orschiro** [comment] 2015-06-09 07:33
> Probably you should try at first running ./mprisctl pause and see if that pauses elementary OS player.

It seems to work, thanks very much! Essentially your `mprisctl` adds support for mps-youtube while remaining compatible with all the default eOS music integration, correct?

> I tried to test elementary OS player that and it seems to support MPRIS correctly, but wasn't able to import any songs (what?).

I can't follow this problem. Can you please explain again?

**Comment by hrnr** [comment] 2015-06-09 09:36
>It seems to work, thanks very much! Essentially your mprisctl adds support for mps-youtube while remaining compatible with all the default eOS music integration, correct?

Yes. This way you should be able to control almost all players.

> I can't follow this problem. Can you please explain again?

Nothing to bother about, if you are using eOS player happily. eOS running live in qemu, just didn't want to import any mp3's for me, so I couldn't test it properly.

Overall, I'm glad it's working for you.

**Closed** 2015-07-12 20:08 UTC
