### ISSUE TITLE
Quota exceeded

### ISSUE THREAD

**Issue by DoRullings** [mps-youtube/mps-youtube#567] opened 2016-12-10 21:33 UTC
I got this error while trying to open mpsyt-0.2.7.1.exe:

> Pafy.util.GdataError: Youtube Error 403: Daily Limit Exceeded. The quota will be
  reset at midnight Pacific Time (PT). Także monitor your quota usage and adjus
h limits in the API Console: https://console.developers.google.com/apis/api/yout
ube / quotas? project = 422897895433

Is this simply because high activity have exceeded the free quota or another plan, or is it an other underlying error? The reason I ask is because that when I try to open the URL you can find in the error above:
Https://console.developers.google.com/apis/api/youtube/quotas?project=422897895433

I get this error:

> The API "youtube" does not exist or you do not have permission to access option it

This might be ice because I'm logged in Google as a user who does not has access to read the quota? I do not know, but I thought you should know and I suspect it is not an intentional behavior and there would consider it as a bug.

Thank you for a great application!

Best regards!
Thomas Gabrielsen

**Comment by jadedml** [comment] 2016-12-10 23:43
Ditto, I've had the exact same problem.
I also just began having this problem.
It's too bad YT is so restrictive with its API as to have a quota at all...

**Comment by tinydynamite00** [comment] 2016-12-10 23:58
@jadedml See #551

**Comment by jadedml** [comment] 2016-12-11 03:50
@tinydynamite00 
Ah, thanks! :) 
Sorry, I probably should've looked deeper in the issue tracker.

**Comment by tinydynamite00** [comment] 2016-12-11 05:50
@jadedml Hi! Does clearing mpsyt's cache have any effect for you? If removing the cache works for you - allows your client to connect - it may help explain why the 403 (Forbidden) errors are being returned by the server.

**Comment by ids1024** [comment] 2016-12-11 17:52
> This might be ice because I'm logged in Google as a user who does not has access to read the quota?

This appears to be the case, since I can access the quota page.

Closing as a duplicate of #551.

**Closed by ids1024** 2016-12-11 17:52 UTC

**Comment by DoRullings** [comment] 2016-12-11 19:40
I am sorry for the duplicate, and thanks for the heads up! I'll try to prevent this from happening in the future.

Best,
Thomas Gabrielsen
