### ISSUE TITLE
Running mpsyt --help causes the terminal text color to stay yellow

### ISSUE THREAD

**Issue by Chronomly** [mps-youtube/mps-youtube#1026] opened 2019-10-22 20:35 UTC
## Issue / Suggestion
I attempted to run `mpsyt --help` and it doesn't reset the terminal font color after changing it to yellow

## Your Environment
0.2.8
Fedora 30
mpv

## Screenshot
https://when-will.disilla.org/be/done/m5PUT2tgXRmn.png

**Comment by Nojus297** [comment] 2019-10-24 12:44
What terminal emulator?

**Comment by Chronomly** [comment] 2019-10-24 13:40
GNOME Terminal with Bash

**Comment by Nojus297** [comment] 2019-10-24 18:48
Well, I'm not sure. I can't reproduce it.

**Comment by Chronomly** [comment] 2019-10-25 14:30
https://when-will.disilla.org/be/done/m5PUT2tgXRmn.png

**Comment by Nojus297** [comment] 2019-10-25 18:21
ccab53b5f0a2779a7d7935bbb81402a3094334a0
#931
Looks like it has been fixed. Try with current develop version.

**Comment by hrnr** [comment] 2019-11-13 20:21
This should be fixed.

**Closed by hrnr** 2019-11-13 20:21 UTC
