### ISSUE TITLE
self._ydl_info['categories'] - TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DoRullings** [mps-youtube/mps-youtube#565] opened 2016-12-05 16:52 UTC
I downloaded and tested this program (mpsyt-0.2.7.1.exe) for the first time today and I searched the help menu all the time, it might important because I haven't been able to replicate the error: 

Commands I remember I runned before the error: 

help basics
help download
search janis joplin ball and chain
d 2
13
[some searches in help menu again]
user dorullings
set search_music False
user dorullings

Then this response:
Searching for 'DoRullings'

Num  Title                                                               Time
 1   Shapes of Nature                                                   02:23
 2   Super low subsonic flyby! Oslo Air Show 2012                       00:26
 3   Little Big Planet                                                  08:43
 4   Promotional video for Mikromarc (a Norwegian library system)       01:22
 5   Useless Arduino project                                            00:33
 6   1 year and 10 months year old boy unlocks iPhone                   00:15
 7   Plenklipping - time for time, minutt for minutt, sekund for sekun  15:17
 8   Joa Ebert's java live coding at Flash on the Beach 2009            09:59

Video uploads by DoRullings
> Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Devel\src\git\mps-youtube\mps_youtube\streams.py", line 171, in _preload
  File "E:\Devel\src\git\mps-youtube\mps_youtube\streams.py", line 51, in get
  File "E:\Devel\src\git\mps-youtube\mps_youtube\util.py", line 201, in get_pafy
  File "E:\Devel\src\git\mps-youtube\pafy\pafy.py", line 122, in new
  File "E:\Devel\src\git\mps-youtube\pafy\backend_youtube_dl.py", line 29, in __init__
  File "E:\Devel\src\git\mps-youtube\pafy\backend_shared.py", line 95, in __init__
  File "E:\Devel\src\git\mps-youtube\pafy\backend_youtube_dl.py", line 53, in _fetch_basic
TypeError: 'NoneType' object is not subscriptable

**Comment by Darkless012** [comment] 2016-12-14 15:14
Including my stack trace

```
Exception in thread Thread-61: 00:00:02 [2%]   [===>                                                                                                                                                                            ] vol: 100%   
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/streams.py", line 171, in _preload
    streamlist = get(song)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.5/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/local/lib/python3.5/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python3.5/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python3.5/dist-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object is not subscriptable

```

This happened when I was switching song in playlist to next one.

**Comment by lol768** [comment] 2016-12-15 14:01
I see this a lot - can't reproduce every time. I've updated youtube-dl and will see if I get this anymore.

**Comment by ids1024** [comment] 2016-12-15 16:38
Changing that line to `self._category = self._ydl_info['categories'][0] if self._ydl_info['categories'] else ''` should probably resolve the issue. Though if it's inconsistent, I don't know why it would happen.

**Comment by lol768** [comment] 2016-12-16 14:55
I've added some debugging code to `backend_youtube_dl.py` to try print some information about the state of things when this happens. My guess is that it's a youtube-dl issue and it's returning garbage/nothing for the categories randomly.

**Comment by ids1024** [comment] 2016-12-19 18:42
@lol768 That is odd. I wonder if it is a youtube-dl bug, or some inconsistency on YouTube's side.

**Comment by DoRullings** [comment] 2016-12-19 20:28
The inconsistency doesn't exactly makes debugging more fun. I haven't been able to replicate the error since so it isn't exactly a huge bug/problem. Not for me at least.

**Comment by lol768** [comment] 2017-02-15 19:05
I still get this a few times a day, it's interesting you can't reproduce it @DoRullings 

> Changing that line to self._category = self._ydl_info['categories'][0] if self._ydl_info['categories'] else '' should probably resolve the issue. Though if it's inconsistent, I don't know why it would happen.

Yes, this does fix it. Whilst getting to the bottom of this would be nice, I feel like a stopgap to prevent the whole program dying could be useful.

I did consider reporting this on youtube-dl's repo but the issue requirements are a bit of a pain to follow, and I can't reliably reproduce this.

**Comment by jkleve** [comment] 2017-09-19 05:14
Started getting this issue too. Looks like it's conditionally checked like @lol768 suggested in [Pafy 0.5.3.1](https://github.com/mps-youtube/pafy/commit/66d0f262dd230a947015b3f1fa114551d3bc2bc1#diff-7d7224a47d2aafb520e7dfbe78b970f9)

I would say this is also an issue in the `youtube_dl` package. In some cases the crazy regex in `youtube_dl/extractor/youtube.py` will fail to extract the `Category` variable from the webpage data. 

  ```
      m_cat_container = self._search_regex(
            r'(?s)<h4[^>]*>\s*Category\s*</h4>\s*<ul[^>]*>(.*?)</ul>',
            video_webpage, 'categories', default=None)

        if m_cat_container:
            ...
        else:
            video_categories = None
```

**Comment by jkleve** [comment] 2017-09-19 05:16
Oh lol. @ids1024 was the one that fixed it...

**Comment by tngotran** [comment] 2018-04-19 02:49
I set the self._category = 'some String here' and it bypasses the error :)

**Comment by SylannBin** [comment] 2018-04-26 17:46
I've installed mps-youtube on raspberry-pi 2B, OS: raspbian without graphical environment.
The installation is fresh.
And I get this error after any search, or url input, sometimes it takes several seconds to happen.

```
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 171, in _preload
    streamlist = get(song)
  File "/usr/lib/python3/dist-packages/mps_youtube/streams.py", line 51, in get
    p = util.get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3/dist-packages/mps_youtube/util.py", line 201, in get_pafy
    p = pafy.new(ytid, callback=callback_fn)
  File "/usr/lib/python3/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3/dist-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by SylannBin** [comment] 2018-04-27 10:58
Thanks Ngo ! It worked.

Out of curiosity, I've noticed that pull-requests tend to take to time to be applied, and things like this bug tend to stay even though a "quick fix" is known.

What is the reason ?

**Comment by jellopudding** [comment] 2019-04-09 08:31
I'd like to just mention that this is still an issue and that the quick fix is still working; I, too, wonder why a fix has been known for some 2 years but the package in the repos have not been fixed.

**Comment by sandeep-gh** [comment] 2020-09-30 15:34
Seems this is still an issue. The workaround still works. Would be good to have this in the package itself.

**Comment by iamtalhaasghar** [comment] 2023-01-27 05:49
was fixed here https://github.com/iamtalhaasghar/yewtube/commit/440ab17108f64316fc74e476715445b939372d69

**Closed by iamtalhaasghar** 2023-01-27 05:49 UTC
