### ISSUE TITLE
Issue when setting playerargs with mpv

### ISSUE THREAD

**Issue by sotlampr** [mps-youtube/mps-youtube#415] opened 2016-01-15 10:00 UTC
I am trying to set playerargs for mpv, let's say I want the video output to libcaca so I must set 

    --vo=caca

I see two ways of doing this:
1. With quotes:

       set playerargs "--vo=caca"

(or the equivalents "-vo=caca", -"-vo caca", "-vo caca" etc.)

What happens is that mpv thinks the arguement is a file, so I have the message "cannot open file "--vo=caca" if I omit the --really-quiet option and, of course, no libcaca output.

2. Without quotes:

        set playerargs --vo=caca

(or the equivalents -vo=caca, --vo caca, -vo caca etc.)

What is happening now is that the video plays as supposed,  i.e. with libcaca output (if i freeze at this point with pdb), BUT after opening the mpv subprocess an error is raised when sending the socket to mprisctl ([main.py, L1262](https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/main.py#L1261)). The error states:

*Problem playing last item: Expecting property name enclosed in double quotes: line 1 column 62 (char 61)*

Any Ideas or suggestions on how to fix this?

S.

**Comment by ids1024** [comment] 2016-01-15 23:21
I can't seem to reproduce this. Try setting a breakpoints at `mps_youtube.main.launch_player` and using `args` to see exactly what command it is trying to execute.

**Comment by sotlampr** [comment] 2016-01-16 09:25
OK, to recap: when using playerargs --vo=caca (without quotes) I get the following errror:

    Problem playing last item: Expecting property name enclosed in double quotes: line 1 column 62 (char 61)

The error comes from [mpris.py, L212](https://github.com/mps-youtube/mps-youtube/blob/develop/mps_youtube/mpris.py#L212) and is this:

    File "./mps-youtube/mps_youtube/mpris.py", line 214, in bindmpv
      resp = json.loads(line)
    File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
      obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: 
    line 1 column 62 (char 61)

the offending line is:

    {"event":"property-change","id":1,"name":"time-pos","data":0,000000}
                                                                ^

Remarkable!!! It has a comma instead of a full stop so the json loader fails to parse it.
Do you have any idea why this might be happening so I can inquire further? 

Thanks
S.

**Comment by hrnr** [comment] 2016-01-16 10:46
This seems to be localization issue. Is your language using commas as decimal point? Could you post your locale?

As json specs does not allow commas in numbers, this must be bug in mpv. Which mpv version are you using?

I'm not really sure, however, why the problem is trigger by using vo=caca on your side.

**Comment by sotlampr** [comment] 2016-01-16 14:01
You are right, the problem was triggered by a non-US LC_NUMERIC setting.
I also tried with the latest mpv from git and the problem was still there (with the non-US locale). You think I should open an issue on mpv or forget about it?

**Comment by hrnr** [comment] 2016-01-16 15:46
Yes, you should, mpv is under active development and in my experince the team is very responsive. Or I could report it for you, if you're not familiar with mpv codebase.

If you also want to attach patch for mpv, here are some pointers:

The problem is in [misc/json.c](https://github.com/mpv-player/mpv/blob/ea442fa047819ec2e48a3dbe8ea21959ac3d70b0/misc/json.c), it prints double via append functions from [misc/bstr.c](https://github.com/mpv-player/mpv/blob/ea442fa047819ec2e48a3dbe8ea21959ac3d70b0/misc/bstr.c), which finally prints your double via `vsnprintf`. It is a locale-aware function from standard library.

The issue could be solved either via setting locale to "POSIX" or "C" via `setlocale` (but it would affect locale for whole program and setting unsetting would be expensive) or use simple hack ","->"." replacement for json (as this is json-only problem - jsons are never locale-aware). This would be probably better, because you want to preserve locale everywhere else.

Hack for double values in json should be put [here](https://github.com/mpv-player/mpv/blob/ea442fa047819ec2e48a3dbe8ea21959ac3d70b0/misc/json.c#L251)

**Comment by ids1024** [comment] 2016-01-30 16:21
Closing this, since the bug seems to be in libcaca (or in mpv, according to the libcaca developer).

**Closed by ids1024** 2016-01-30 16:21 UTC
