### ISSUE TITLE
Add "back button" to the mpsyt.

### ISSUE THREAD

**Issue by ZaxonXP** [mps-youtube/mps-youtube#762] opened 2018-01-18 15:15 UTC
## Issue 

Currently if search is done for the user playlists and later on some playlist is opened, then there is no other way to go back to the user playlist search results than doing again the user playlist search.

## Suggestion
It would be nice to have a "back" buton, which would go the the previous search results. Simillar like it is done in a normal web browser. The `b` key seems to be not used by anything.

**Comment by Vrihub** [comment] 2018-01-21 12:11
I guess this is a duplicate of #523

**Comment by ZaxonXP** [comment] 2018-01-23 09:37
Indeed it is the same. Sorry for making a duplicate.

**Closed** 2018-01-23 09:37 UTC
