### ISSUE TITLE
mpsyt problem playing last item

### ISSUE THREAD

**Issue by StylinGreymon** [mps-youtube/mps-youtube#952] opened 2019-02-26 20:32 UTC
When trying to watch a video, mpsyt throws this error:
>Problem playing last item: Expecting value: line 1 column 1 (char 0)
>
and returns to search results

## Your Environment
>mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2019.02.18
Python version     : 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, 
Platform           : Linux-4.20.10-1-MANJARO-x86_64-with-arch-Manjaro-Linux
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/greymon/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /bin/zsh
env:LANG           : en_US.UTF-8

## Video Player
>mpv 0.29.0-134-g8b563a0346 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects                                        
 built on Wed Feb 20 18:22:26 PST 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.47.102
   libavformat     58.26.101
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: N-93158-gc8bc9d1380

Running mpsyt with the --logging flag shows this:
>DEBUG:root:input: q
DEBUG:root:function call: quits
DEBUG:root:regx matches: ()
DEBUG:root:Saved history file
DEBUG:root:[95msaved cache file: /home/greymon/.config/mps-youtube/cache_py_3.7.2[0m
DEBUG:root:Unrecognised config item: SHOW_PLAYER_KEYS
DEBUG:root:Unrecognised config item: LOOKUP_METADATA
DEBUG:root:Unrecognised config item: SHOW_QRCODE
DEBUG:root:[92mRead history file[0m
DEBUG:root:[92m10 cached streams imported[0m
DEBUG:root:[94mpaf: 0, streams: 10[0m
DEBUG:root:transcoding config file exists
DEBUG:root:searching path for mpv
DEBUG:root:found at /bin/mpv
DEBUG:root:mpv version 0.29.0 detected
DEBUG:root:[92mmpv supports --input-ipc-server[0m
DEBUG:root:searching path for ffmpeg
DEBUG:root:found at /bin/ffmpeg
DEBUG:root:input: userpl redlettermedia
DEBUG:root:function call: user_pls
DEBUG:root:regx matches: ('redlettermedia',)
DEBUG:root:input: 8
DEBUG:root:function call: play
DEBUG:root:regx matches: ('', '8', '')
DEBUG:root:[93mFetching playlist using pafy[0m
DEBUG:root:[93mpreload: got new pafy object: Best of the Worst: Wheel o[0m
DEBUG:root:[93mpreload: got new pafy object: FT5D7rJ8TPQ[0m
DEBUG:root:[94mpaf: 1, streams: 11[0m
DEBUG:root:select stream, q: 0, audio: False, len: 3
DEBUG:root:[93mpreload: getting content-length header[0m
DEBUG:root:[93mpreload:  - content-length: 215167831[0m
DEBUG:root:input: 7
DEBUG:root:function call: play
DEBUG:root:regx matches: ('', '7', '')
DEBUG:root:[93mgot new pafy object: Best of the Worst: Lycan C[0m
DEBUG:root:[93mgot new pafy object: 5nQYdtaH41k[0m
DEBUG:root:[94mpaf: 2, streams: 12[0m
DEBUG:root:select stream, q: 0, audio: False, len: 5
DEBUG:root:searching path for mpv
DEBUG:root:found at /bin/mpv
DEBUG:root:[93mgetting content-length header[0m
DEBUG:root:[93m - content-length: 161583720[0m
DEBUG:root:playing Best of the Worst: Lycan Colony
DEBUG:root:calling mpv --title Best of the Worst: Lycan Colony --no-ytdl --really-quiet https://r1---sn-nx5s7n7s.googlevideo.com/videoplayback?id=e6741876d687e359&itag=22&source=youtube&requiressl=yes&mm=31,29&mn=sn-nx5s7n7s,sn-nx57ynlz&ms=au,rdu&mv=m&pl=22&ei=wZ91XLWROIijkgalnrnwBg&susc=yt&initcwndbps=1735000&mime=video/mp4&ratebypass=yes&dur=2563.320&lmt=1547761156879012&mt=1551212396&fvip=1&beids=9466586&c=WEB&txp=5535432&ip=73.96.109.9&ipbits=0&expire=1551234082&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ei,susc,initcwndbps,mime,ratebypass,dur,lmt&signature=B89BE2299D0594D6CA084FEAFC5159DFFE0518FF.0570CB4BA779CE83447077010B09CD7AC6B530B1&key=yt8
DEBUG:root:[93mpreload: got new pafy object: Best of the Worst: Night o[0m
DEBUG:root:[93mpreload: got new pafy object: m0QUo5jnhYE[0m
DEBUG:root:[94mpaf: 3, streams: 13[0m
DEBUG:root:select stream, q: 0, audio: False, len: 5
DEBUG:root:[93mpreload: getting content-length header[0m
DEBUG:root:[93mpreload:  - content-length: 522439947[0m

**Comment by Vrihub** [comment] 2019-02-27 19:28
Duplicate of #953

**Comment by pirate486743186** [comment] 2019-04-09 17:53
@StylinGreymon 
You can close this issue....

**Closed** 2019-04-09 18:28 UTC
