### ISSUE TITLE
Keep playing the video when we press the "r" key

### ISSUE THREAD

**Issue by hillz1** [mps-youtube/mps-youtube#564] opened 2016-11-18 19:21 UTC
Is it possible to keep playing the video or song in the background when we press the "r" key to return to the search result? It's a bit uncomfortable if you can't still listen to the song while reading the search result

**Comment by ids1024** [comment] 2016-11-20 19:59
Duplicate of #127.

Playing in the background is mildly complicated to implement, for various reasons.

**Closed by ids1024** 2016-11-20 19:59 UTC
Labels: duplicate
