### ISSUE TITLE
Channel subscription system

### ISSUE THREAD

**Issue by jtviera** [mps-youtube/mps-youtube#322] opened 2015-07-01 23:18 UTC
Some kind of channel subscription system, or integration for youtube's subscription system would be useful.
This is currently the reason why I can't exclusively use mpsyt for browsing youtube.

**Comment by ids1024** [comment] 2015-07-10 23:33
Duplicate of #157.

This has been requested a lot and I agree it is a good feature. I currently have various other features to work on, but if someone else is interested in implementing this, pull requests are welcome.

**Closed by ids1024** 2015-07-10 23:33 UTC
